services:
  postgres:
    image: postgres:16-alpine
    container_name: collaborative_engine_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: collab_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # This runs our setup scripts automatically

volumes:
  postgres_data: